import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import useSWR from "swr";
import { ProductDto } from "./api/products";

const Home: NextPage = () => {
  const fetcher = (url: string) => fetch(url).then((res) => res.json());

  const { data, error } = useSWR<ProductDto[]>("/api/products", fetcher);

  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;

  return (
    <div className="container mx-auto">
      <Head>
        <title>Czar Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Products products={data} />
    </div>
  );
};

export default Home;

type ProductsProps = {
  products: ProductDto[];
};
function Products({ products }: ProductsProps) {
  return (
    <div className="container columns-4 pt-2 px-2 py-4 space-y-2">
      {products.map((product) => (
        <Product key={product._id} product={product} />
      ))}
    </div>
  );
}

type ProductProp = {
  product: ProductDto;
};
function Product({ product }: ProductProp) {
  const { _id, image_url, name, value } = product;
  return (
    <div className="max-w-sm rounded overflow-hidden hover:border-4">
      <Image
        className="w-full"
        src={`/images/${image_url}`}
        alt="Sunset in the mountains"
        width="360"
        height="360"
      />
      <div className="px-6 py-4">
        <div className="text-orange-500 font-bold text-xl mb-2">{name}</div>
        <p className="text-orange-500 text-base text-center font-medium">
          {value}
        </p>
      </div>
    </div>
  );
}
